### 학생 등록 테스트
POST http://localhost:8080/students
Content-Type: application/json

{
  "studentNumber": "20240618442",
  "name": "김형석",
  "email": "test@sparta.com"
}

### 학생 조회 테스트
GET http://localhost:8080/students/1

### 학생 점수 등록 테스트
POST http://localhost:8080/students/1/test
Content-Type: application/json

{
  "studentId": 1,
  "score": 90.0,
  "subjectType": "JPA"
}

### 학생 점수 조회 테스트
GET http://localhost:8080/students/1/test
Content-Type: application/json

{
  "studentId": 1,
  "subjectType": "JPA"
}

### 학생 학번 조회 테스트
GET http://localhost:8080/students?number=20240614
